class Cons:
    OPC_1: str = "1"
    OPC_2: str = "2"
    OPC_3: str = "3"
    OPC_4: str = "4"
    OPC_5: str = "5"
    OPC_6: str = "6"
    OPC_7: str = "7"
    OPC_8: str = "8"
    SEPARADOR: str = "-"
